### ISSUE TITLE
Implement 2d sel via Xarray accessor?

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/xoak#1]
We have <https://git.geomar.de/python/xorca_lonlat2ij> which basically
- puts all horizontal coordinates into 3d space referenced to the center of the earth.
- constructs a KD tree
- looks up closest indices for any given `lat`, `lon` pair

([`xorca_lonlat2ij.get_ij`](https://git.geomar.de/python/xorca_lonlat2ij/-/blob/7e39cc7a880f8fa10f1732b504e64614bbad562c/xorca_lonlat2ij/__init__.py#L217) is a good entry point to get an overview of the logic.)

Then, we usually use these indices for a vector `.sel()` as seen here <https://github.com/ESM-VFC/esm-vfc-workflows/blob/7edd9bbc7cd3532c0537f89f667154a9dd27156d/meteor_m85.1_vs_NEMO_FOCI_hydrography/compare_m81.1_hydrography_with_ORCA05_FOCI_Test_data.ipynb>

What I'd like to have is this implemented as an [Xarray accessor](http://xarray.pydata.org/en/stable/generated/xarray.register_dataset_accessor.html) or something that is similarly easy to use.

This would not act on the staggered C grids, we'll need XGCM for, but could be easily generalized to XGCM-compatible datasets if <https://github.com/xgcm/xgcm/issues/200> became reality at a later point.

(@benbovy This could be a first thing to work on.)

**Comment by benbovy** [comment]
Great, thanks!

I don't have strong opinion about package structure. I haven't used poetry yet. Recently I've started putting source files under `src/` and I'm happy with it.

Do you mind if I have commit rights on this repo? I'll continue contributing through PRs anyway.

**Comment by willirath** [comment]
I think you have them per your status in ESM-VFC. Let me check...

**Comment by willirath** [comment]
@benbovy Can you see if you could (in principle) merge #3?

**Comment by benbovy** [comment]
There's no visible merge button on my side.

**Comment by benbovy** [comment]
It works now, thanks!

**Comment by willirath** [comment]
Needed to add write access per repository. I've added you as full admin.
