### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by benbovy** [ESM-VFC/xoak#29]
TODO (before release):

- [x] more indexes #28 (ready to merge) 
- [x] more test coverage (accessor)
- [x] Github action for uploading to Pypi + update release notes (doc) + update doc and readme with install instructions.

TODO (just after release):

- [x] submit PR to conda-forge staged recipe

@willirath do you think about anything else?

**Comment by willirath** [comment]
I don't see anything else that needs to happen.

Will you add the Pypi package, or should I do something there?

**Comment by benbovy** [comment]
> Will you add the Pypi package, or should I do something there?

This should be done automatically by a github action added in #31.
