### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/xoak#6]
(From https://github.com/ESM-VFC/xoak/pull/3#pullrequestreview-438701996.)

- [ ] test the `XoakAccessor` index property
- [ ] test non-transformed coordinate values (perhaps with other data than geo coordinates)
- [ ] test NN lookup tolerance
- [ ] check that the order of coordinate labels in the returned selection is preserved (I checked this locally simply  by inspecting the results and it works)
- [ ] shallow test for the `DataArray.xoak` accessor

**Comment by benbovy** [comment]
Closed in #10, #30.
